// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqA4M2ag5ok0HcZoGCjAsFbkQAbEnRFsQ',
    appId: '1:789743203068:web:8955d771417243ad835d79',
    messagingSenderId: '789743203068',
    projectId: 'melodic-mania',
    authDomain: 'melodic-mania.firebaseapp.com',
    storageBucket: 'melodic-mania.appspot.com',
    measurementId: 'G-X9HN3MKM36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXEw3lZ_b48mWH_W2dSb9KBaX-iFFnhHE',
    appId: '1:789743203068:android:ee39c41b86e59842835d79',
    messagingSenderId: '789743203068',
    projectId: 'melodic-mania',
    storageBucket: 'melodic-mania.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEGrgAsp10Q5gq0zIHlQREDHRhEPYUi0I',
    appId: '1:789743203068:ios:a0b170c2424bdbff835d79',
    messagingSenderId: '789743203068',
    projectId: 'melodic-mania',
    storageBucket: 'melodic-mania.appspot.com',
    androidClientId: '789743203068-rm8iolep657v2omnvvaqeocmf7p7k0s6.apps.googleusercontent.com',
    iosClientId: '789743203068-on247csj96a6e8ccd6dstrqu4egnpjd6.apps.googleusercontent.com',
    iosBundleId: 'com.melodymania.songbird',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEGrgAsp10Q5gq0zIHlQREDHRhEPYUi0I',
    appId: '1:789743203068:ios:a0b170c2424bdbff835d79',
    messagingSenderId: '789743203068',
    projectId: 'melodic-mania',
    storageBucket: 'melodic-mania.appspot.com',
    androidClientId: '789743203068-rm8iolep657v2omnvvaqeocmf7p7k0s6.apps.googleusercontent.com',
    iosClientId: '789743203068-on247csj96a6e8ccd6dstrqu4egnpjd6.apps.googleusercontent.com',
    iosBundleId: 'com.melodymania.songbird',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqA4M2ag5ok0HcZoGCjAsFbkQAbEnRFsQ',
    appId: '1:789743203068:web:c0d5e99e2914382f835d79',
    messagingSenderId: '789743203068',
    projectId: 'melodic-mania',
    authDomain: 'melodic-mania.firebaseapp.com',
    storageBucket: 'melodic-mania.appspot.com',
    measurementId: 'G-F579P5FZ94',
  );

}